config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:create] do
    collection do
      get :sign_up, action: 'new'
      # get :sign_in, action: 'new'
      #可以放在同一個裡面。
    end
  end

  resources :sessions, path: 'users', only: [] do
    collection do
      get :sign_in, action: 'new'
      post :sign_in, action: 'create'
    end
  end

  resources :candidates
  root 'candidates#index'

  
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  validates :name, presence: true

  # def self.available
  #   where(deleted_at: nil)
  # end

  def self.deleted
    unscope(:where).where(deleted_at: nil)
    #因為預設是where nil，所以要先拿掉預設才查得到
  end


  scope :available, -> { where(deleted_at: nil)}
  # scope :unavailable, -> { where.not(deleted_at: nil)}
  #      參數一           參數二
  #scope目的是做出一個範圍、篩子
  # lambda, proc => 物件化的block



  def destroy
    #一般使用者
    update(deleted_at: Time.now)
  end

  def real_destroy!
    # 實體方法:給系統管理者使用
    # destroy
    #會呼叫上面的假刪除

    super.destroy
    #呼叫上一層的destroy方法
  end

end

app/models/user.rb
=======================================================
   0413
   Class Cat
    def self.a
      new.b
      Cat.new.b  #or
      Cat.new.b  # or
      self.new.b  #or

    end

    def b
    end
  end

# ororororoor
把模組當作容器工具用，所以不使用include，把module當作class使用，變成方法的一部分
  module xx
    def self.b
    end
  end

  class Cat 
    def self.a 
      X.b
    end

    def b
      X.b
    end
  end

================================================================
  #  module Encryptor
  # class Hasher
  module Hasher
    require 'digest'
    def self.encrypt(cccc)
      Digest::SHA1.hexdigest(cccc)
    end

    def self.salted(pdddd)
      "123#{pdddd}xx"
    end
  end
放在models外面，此例放在這裡可以
做出CCC.encrypt('123')
不需要先呼叫一個物件出來再呼叫方法

下面再呼叫Hasher↓↓↓↓↓↓↓↓↓↓↓↓↓↓


def self.login(params)
  email = params[:email]
  password = params[:password]

  salted_password = Hasher.salted(password)
  encrypted_password = Hasher.encrypted(salted_password)

  find_by(email: email, password: encrypted_password)
end

private
def encrypt_password
  salted_pwd = Hasher.salted(password)
  self.password = HAsher.encrypt(salted_pwd)
end

# def encrypt(password)
#   Digest::SHA1.hexdigest(password)
# end

# def salted(password)
#   "123#{password}xx"
# end
  ====================================================================


class User < ApplicationRecord
  # attr_writer :password_confirmation
  # validates :email, presence: true, uniqueness: true
  validates :email, presence: true,
                    uniqueness: true, 
                    format: { with: /.+\@.+\..+/ }
  validates :password, presence: true,
                       confirmation: true

before_create :encrypt_password


  # private
  # def encrypt_password
  #   self.password = Digest::SHA1.hexdigest(self.password)
  #   # self.password = Digest::SHA1.hexdigest(password)
  #   # self.password=(Digest::SHA1.hexdigest(password))
  #   # password = Digest::SHA1.hexdigest(password)
  # end

  # def self.login(params)
  #   email = params[:email]
  #   password = params[:password]

  #   encrypted_password = encrypted(salted(password))

  #   find_by(email: email, password: encrypted_password)
  # end
  # def self.login(params)
  #   email = params[:email]
  #   password = params[:password]

  #   salted_password = salted(password)
  #   encrypted_password = encrypted(salted_password)

  #   find_by(email: email, password: encrypted_password)
  # end

  # private
  # def encrypt_password
  #   salted_pwd = salted(password)
  #   self.password = encrypt(salted_pwd)
  #   # self.password = Digest::SHA1.hexdigest(password)
  #   # self.password=(Digest::SHA1.hexdigest(password))
  #   # password = Digest::SHA1.hexdigest(password)
  # end

  # def encrypt(password)
  #   Digest::SHA1.hexdigest(password)
  # end

  # def salted(password)
  #   "123#{password}xx"
  # end


  def self.login(params)
    email = params[:email]
    password = params[:password]

    salted_password = salted(password)
    encrypted_password = encrypted(salted_password)

    find_by(email: email, password: encrypted_password)
  end

  private
  def encrypt_password
    salted_pwd = salted(password)
    self.password = encrypt(salted_pwd)
    # self.password = Digest::SHA1.hexdigest(password)
    # self.password=(Digest::SHA1.hexdigest(password))
    # password = Digest::SHA1.hexdigest(password)
  end

  def encrypt(password)
    Digest::SHA1.hexdigest(password)
  end

  def salted(password)
    "123#{password}xx"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def index
    # @candidates = Candidate.all
    # @candidates = candidate.where(deleted_at:nil)
    @candidates = Candidate.available
  end

  # def index_deleted
  #   @candidate = Candidate.deleted
  # end


  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidates_params)
    if @candidate.save
      #成功
      # flash[:notice] = "ha"
      redirect_to candidates_path, notice: "新增成功"
    else
      #失敗
      render :new
    end
  end

  def edit
    @candidate = Candidate.find_by(id: params[:id])
  end

  def update
    @candidate = Candidate.find_by(id: params[:id])
    # byebug
    if @candidate.update(candidates_params)
      redirect_to candidates_path, notice: "更新成功"
    else
      render :edit
    end
  end

  # def self.all
  #   # where(deleted_at: nil)
  #   #會造成無窮迴圈
  # end
  
  def destroy
    @candidate = Candidate.find_by(id: params[:id])
    # @candidate.destroy if @candidate  #真刪除
    # @candidate.update(deleted_at: Time.now) #假刪除
    @candidate.destroy if @candidate
    #在上層定義一個destroy假刪除
    redirect_to candidates_path, notice: "已刪除"
  end
  
  private
  def candidates_params
    params.require(:candidate).permit(:name, :age, :party, :politics)
  end

  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end
  
  # def create
  #   email = params[:user][:email]
  #   password = params[:user][:password]
  #   render html: params
  #   # 1 查有無帳號 / 密碼
  #   # 2 轉址 / 重登
  # end

  # def create
  #   email = user_params[:email]
  #   password = user_params[:password]
  #   render html: params
  #   # 1 查有無帳號 / 密碼
  #   # 2 轉址 / 重登
  # end

  def create
    if User.login(user_params)
      # 發號碼牌
      # 轉去首頁
      redirect_to root_path
    else
      redirect_to sign_in_sessions_path
    end
  end

  private 
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    # if user_params[:password] == user_params[:password_confirmation]

    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/candidates/_form.html.erb
<%= form_for(candidate) do |f| %>
  <%= f.label :name, "姓名" %>
  <%= f.text_field :name %> <br />

  <%= f.label :age, "年齡" %>
  <%= f.text_field :age %> <br />

  <%= f.label :party, "政黨" %>
  <%= f.text_field :party %> <br />

  <%= f.label :politics, "政見" %>
  <%= f.text_area :politics %> <br />

  <%= f.submit %>
<% end %>

app/views/candidates/edit.html.erb
<h1>編輯候選人</h1>

<%= render "form", candidate: @candidate %>


<br />
<%= link_to '回候選人列表', candidates_path %>

app/views/candidates/index.html.erb
<h1>候選人列表</h1>

<%= link_to "新增候選人", new_candidate_path %>

<table>
  <thead>
    <tr>
      <td>投票</td>
      <td>候選人姓名</td>
      <td>年齡</td>
      <td>政黨</çtd>
      <td>政見</td>
      <td>得票數</td>
      <td>處理</td>
    </tr>
  </thead>
  <tbody>
    <% @candidates.each do |candidate| %>
    <tr>
      <td><%= link_to "投給這位", "#" %></td>
      <td><%= link_to candidate.name, candidate_path(candidate.id) %></td>
      <td><%#= candidate.name %></td>
      <td><%= candidate.age %></td>
      <td><%= candidate.party %></td>
      <td><%= candidate.politics %></td>
      <td><%= candidate.vote %></td>
      <td>
        <%= link_to "edit", edit_candidate_path(candidate) %>
        <%= link_to "刪除", candidate_path(candidate), method: "delete", data: { confirm: "確認刪除" } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/candidates/new.html.erb
<h1>新增候選人</h1>

<%= render "form", candidate: @candidate %>

<br />
<%= link_to "回候選人列表", candidates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoteSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    # <% flash.each do |key, value| %>
    #   <div>
    #   <%= value %>
    #   </div>
    # <% end %>  
    <%= yield %>
    <%= notice %>
  </body>
</html>

app/views/users/new.html.erb
<h1>註冊帳號</h1>

<%= form_for(@user) do |form| %>
  <% if @user.errors.any? %>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <%= form.submit %>
<% end %>